#!/bin/bash
BRANCH=$(echo $2 | sed -e "s|origin/||g")
echo $BRANCH
if [ $BRANCH = "main" ]
then
    docker build -t zhima1mochi2/tw-stock-data-transformation data-transformation
    docker push zhima1mochi2/tw-stock-data-transformation
fi